run:
  timeout: 5m
  build-tags: "test"
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - errname
    - goimports
    - govet
    - prealloc
    - predeclared
    - revive
    - staticcheck

linters-settings:
  revive:
    rules:
      - name: package-comments
        disabled: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - ../../.local
    - ../../go
